services:
  - type: web
    name: printune-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
    disk:
      name: data-disk
      mountPath: /mnt/data
      sizeGB: 1
